apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels: 
    apps: nginx
spec:
  ports:
  - name: http
    ports: 80
    protocols: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer  